### ISSUE TITLE
Why use shared mem to store c_frag?

### ISSUE THREAD

**Issue by Pzzzzz5142** [Yinghan-Li/YHs_Sample#2]
The function [here](https://github.com/Yinghan-Li/YHs_Sample/blob/d05b5c93ccaf3aaffa3d51a9707ac63127dd7f3c/cuda/gemm/sgemm.cu#L135) use two `__syncthreads()` and shared mem to store values from c_frag to global memory. As I've noticed that in cuda samples, nvidia did the same thing.

For the extra write to the shared memory and `__syncthreads()` seem to be unnecessary and time consuming, the only benefit I can see from the comment of the cuda samples is the streaming write.  My question is that why don't we store the values directly to global memory and why streaming write could be faster than direct write?

**Comment by Yinghan-Li** [comment]
The output matrix mapped to thread by 2\*2 * 4\*4 for matrix multiplication.

If store the output matrix directly to global memory, for coherent memory access, each thread must store 4 elements at once (ST.128 instruction), and the address must be 16B aligned, it's not flexible.

**Comment by Pzzzzz5142** [comment]
Thanks, that resolves my confusion.
